# Site data

title: "UP System Information Technology Foundation"
titleAlt: "UPSITF"


baseurl: http://toffmendoza.me/sandbox-upsitf
#baseurl: http://upsitf.org/

# Build settings
markdown: kramdown
permalink: pretty

# Site settings
headerDropdown: false

switchBlog: false


urlRegForm: "https://sitf.typeform.com/to/tXnMb4"
urlY4iT: "http://y4it.org"
urlTBC4K: "http://tbc4k.upsitf.org"

urlFacebook: "https://www.facebook.com/upsitf.org/"
urlTwitter: "https://twitter.com/upsitf"

contactAddress:
 - "Rm. 303 Vidal Tan Hall"
 - "Quirino Ave. cor. Velasquez St."
 - "UP Diliman, Quezon City"
contactHours:
 - "8am to 5pm"
contactEmail: "info@upsitf.org"
contactLandline: “(02) 436 2217”
contactFax: “(02) 920 2036”
contactMobile: “0917 563 5682”
