# Site data

title: UPSITF

baseurl: http://toffmendoza.me/sandbox-upsitf
#baseurl: http://upsitf.org/

# Build settings
markdown: kramdown
permalink: pretty

# Site settings
headerDropdown: false

switchBlog: false


urlRegForm: "https://sitf.typeform.com/to/tXnMb4"
urlY4iT: "http://y4it.org"
urlTBC4K: "http://tbc4k.upsitf.org"

urlFacebook: "https://www.facebook.com/upsitf.org/"
urlTwitter: "https://twitter.com/upsitf"
